# Generated by Django 4.0.2 on 2023-02-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorFirstName', models.CharField(max_length=30)),
                ('DoctorLastName', models.CharField(max_length=30)),
                ('DoctorPhoneNumber', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'healthclinic_doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientFirstName', models.CharField(max_length=30)),
                ('PatientLastName', models.CharField(max_length=30)),
                ('PatientJMBG', models.IntegerField(unique=True)),
                ('PatientAddress', models.CharField(max_length=30)),
                ('PatientPhoneNumber', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'healthclinic_patient',
            },
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=30)),
                ('ServiceId', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'healthclinic_typeofservice',
            },
        ),
        migrations.CreateModel(
            name='SchedulingLoggedout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lPatientFirstName', models.CharField(max_length=30)),
                ('lPatientLastName', models.CharField(max_length=30)),
                ('lPatientJMBG', models.IntegerField(unique=True)),
                ('lPatientAddress', models.CharField(max_length=30)),
                ('lPatientPhoneNumber', models.CharField(max_length=30)),
                ('lScheduleName', models.CharField(max_length=30)),
                ('lScheduleDateAndTime', models.DateTimeField(unique=True)),
                ('lScheduleDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.doctor')),
                ('lScheduleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.typeofservice')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScheduleName', models.CharField(max_length=30)),
                ('ScheduleDateAndTime', models.DateTimeField(unique=True)),
                ('ScheduleDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.doctor')),
                ('ScheduleLoggedout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.schedulingloggedout')),
                ('SchedulePatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.patient')),
                ('ScheduleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.typeofservice')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='PatientLoggedout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.schedulingloggedout'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='DoctorType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclinicapp.typeofservice'),
        ),
    ]
